### ISSUE TITLE
Can't run locally

### ISSUE THREAD

**Issue by AaronSikes** [emberjs/api#31]
Installed dependencies.
I have ember.js cloned as a sibling
Ran with this command:
```
ember server   --lib-dir=../ember.js \
 --default-index=Ember \
 --default-module=ember\
 --github-url=https://github.com/emberjs/ember.js\
 --rev=v1.13.1\
 --environment=production\
 --project-name=ember.js
```
On startup I get this output:
```
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/aaron/dev/api/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
version: 0.2.2

A new version of ember-cli is available (1.13.1). To install it, type ember update.
The option '--lib-dir' is not registered with the serve command. Run `ember serve --help` for a list of supported options.
The option '--default-index' is not registered with the serve command. Run `ember serve --help` for a list of supported options.
The option '--default-module' is not registered with the serve command. Run `ember serve --help` for a list of supported options.
The option '--github-url' is not registered with the serve command. Run `ember serve --help` for a list of supported options.
The option '--rev' is not registered with the serve command. Run `ember serve --help` for a list of supported options.
The option '--project-name' is not registered with the serve command. Run `ember serve --help` for a list of supported options.
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/aaron/dev/api/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
Deprecation warning: sassOptions should be moved to your Brocfile
Livereload server on port 35729
Serving on http://localhost:4200/ember.js/v1.13.1/
util.error: Use console.error instead
info: (yuidoc): YUIDoc Starting from: packages/ember/lib,packages/ember-debug/lib,packages/ember-metal/lib,packages/ember-runtime/lib,packages/ember-views/lib,packages/ember-htmlbars/lib,packages/ember-routing/lib,packages/ember-routing-htmlbars/lib,packages/ember-routing-views/lib,packages/ember-application/lib,packages/ember-testing/lib,packages/ember-extension-support/lib,bower_components/rsvp/lib
Can not find directory: bower_components/rsvp/lib [string exception]
Error: Can not find directory: bower_components/rsvp/lib [string exception]
    at /Users/aaron/dev/api/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:36:15
    at lib$rsvp$$internal$$tryCatch (/Users/aaron/dev/api/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/aaron/dev/api/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/aaron/dev/api/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$$internal$$publishRejection (/Users/aaron/dev/api/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:415:7)
    at lib$rsvp$asap$$flush (/Users/aaron/dev/api/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```
And when I try to hit `http://localhost:4200/ember.js/v1.13.1/` I get `Cannot GET /v1.13.1/`

**Comment by trek** [comment]
You to ensure that any project you're building for has all of its dependencies loaded. In this case, `../ember.js` is missing RSVP.
